project:
  type: book
  output-dir: docs

book:
  title: "המדריך העברי למשתמש ב-R"
  author: "דר' עדי שריד"
  date: today
  date-format: iso
  chapters:
    - index.Rmd
    - 01-introduction.qmd
    - 02-base-R.Rmd
    - 03-data-munging-tidyverse.Rmd
    - 04-visualizations-ggplot2.qmd
    - 05-pivot-and-join.qmd
    - 06-hypothesis-tests.qmd
    - 07-linear-regression.qmd
    - 08-advanced-models.qmd
    - 09-purrr.qmd
    - 10-hebrew-in-R.qmd
    - about.Rmd
    - references.qmd
  page-footer: 
    background: "#40b3f6"
    foreground: "#ffffff"
    center:
       - text: >
          <strong>המדריך העברי למשתמש ב-R</strong> נכתב על ידי עדי שריד
          בהוצאת <a href='https://www.sarid-ins.com'>מכון שריד</a>
    left:
       - text: >
           <script async src="https://www.googletagmanager.com/gtag/js?id=G-B91GCMKVW9"></script>
           <script>window.dataLayer = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag("js", new Date()); gtag("config", "G-B91GCMKVW9");
           </script>
  site-url: https://www.hebrewr.co.il
  repo-url: https://www.github.com/adisarid/hebrewr
  #navbar: true

bibliography: references.bib

format:
  html:
    toc: true
    toc-title: "בעמוד זה"
    theme: cosmo
    css: style.css
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px
      
callout-appearance: default


editor: visual